# Generated by Django 5.0.4 on 2024-04-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_goal_delete_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='course',
            name='recurring_fee',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
