# Generated by Django 5.0.4 on 2024-04-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_category_options_course_recurring_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='recurring_fee',
            field=models.BooleanField(default=False),
        ),
    ]
