# Generated by Django 5.0.4 on 2024-04-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_course_recurring_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='recurring_fee',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1),
        ),
    ]
