# Generated by Django 5.0.4 on 2024-04-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_course_recurring_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='url',
            field=models.CharField(default='https://the-creators-growth-club.teachery.co/dashboard', max_length=100),
            preserve_default=False,
        ),
    ]
