# Generated by Django 5.0.4 on 2024-04-10 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_course_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ManyToManyField(blank=True, to='main_app.category'),
        ),
    ]
