# Generated by Django 5.0.4 on 2024-04-10 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_course_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=250)),
                ('date', models.DateField()),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.course')),
            ],
        ),
    ]
